module.exports = [
  //Not putting them in TXT files just because lazy.
  "Random Rants+ is summoning chaos. Please stand by.",
  "Loading mayhem... please wait responsibly.",
  "Bringing the nonsense online. Hold tight.",
  "Please wait while Random Rants+ bootlegs itself into existence.",
  "Loading: This might take a moment—or an eternity.",
  "Booting up the nonsense core...",
  "Starting the digital hallway fight...",
  "Summoning Jason Touch… cross your fingers.",
  "Randomizing the room names and chaos seed…",
  "We're still pretending this is productive. Hang on.",
  "Synchronizing with school Wi-Fi chaos matrix...",
  "Deploying noise. Brace yourself.",
  "Converting focus time into distraction fuel...",
  "Injecting memes into the HTML...",
  "Starting background chaos...",
  "Loading jokes that might get you detention...",
  "Loading... because instant chaos is too powerful.",
  "Loading mysterious glitch energy...",
  "Loading voice chat mayhem...",
  "Loading soundboard spam...",
  "Loading volume over 9000...",
  "Injecting Random into the Rants... almost there.",
  "Loading highly unstable soundboard physics...",
  "Injecting unfiltered hallway drama into RAM...",
  "Enabling turbo-mic mode... scream responsibly.",
  "Generating ‘totally normal’ AI characters...",
  "Stabilizing your friend's laggy potato Chromebook...",
  "Connecting to school Wi-Fi... success? (somehow)",
  "Buffering... because someone opened 9 tabs of YouTube and RR+.",
  "Calibrating chaos engine... please wear headphones.",
  "Unleashing forbidden bracket codes...",
  "Reanimating crashed tabs from the void...",
  "Running on caffeine, memes, and spaghetti code...",
  "Summoning a room full of people who forgot headphones.",
  "Loading chat history with 237 unhinged arguments...",
  "Uploading all known ways to break ;crashTab...",
  "Installing updates for a Chromebook from 2012...",
  "Detecting a teacher. Activating stealth mode.",
  "Fusing school fights with low-res video feeds...",
  "Loading 47 people all trying to spam ;shake at once...",
  "Enabling background chaos even with the lid closed...",
  "Fetching the most cursed camera feeds known to man...",
  "Merging duplicate usernames into one chaotic being...",
  "Reviving crashed logs just to crash again...",
  "Converting keyboard rage into network packets...",
  "Finding the exact moment the mic peaked the loudest...",
  "Aligning the vibe satellites for maximum absurdity...",
  "Downloading memes with questionable educational value...",
  "Launching RR+ on a printer. Why not?",
  "Compiling 800 sound effects into one audio spike...",
  "Holding onto your sanity… failed.",
  "Making Random Rants + even more unhinged...",
  "Trying not to stream your homework folder...",
  "Deploying screen-sharing goblins 👾",
  "Loading code created with school glue...",
  "Making sure your Chromebook is not ready for this...",
  "Loading a 480p video file for no reason...",
  "Talking to ChatGPT about what is going on here...",
  "Getting ready to fry your Chromebooks speakers...",
  "Spawning chaos gremlins into your audio channel...",
  "Buffering sarcasm. Please maintain eye rolls.",
  "Temporarily disabling logic for optimal nonsense...",
  "Converting hallway echoes into stereo lag...",
  "Assembling the digital lunch table gossip...",
  "Ping-ponging your mic input through 5 servers...",
  "Stuck in a boot loop of pure randomness...",
  "Loading glitchy bracket codes from the void...",
  "Rebooting the chaos capacitor… please wait.",
  "Synchronizing chat delay with real-time drama...",
  "Injecting cursed memes into the data stream...",
  "Translating hallway energy into voice distortion...",
  "Preloading 10,000 soundboard taps. Sorry in advance.",
  "Simulating productive learning... failed.",
  "Connecting your signal through 17 VPN tunnels...",
  "Scrambling usernames for maximum confusion...",
  "Activating advanced drama rendering system...",
  "Decoding lag into a new language...",
  "Waiting for your Chromebook to remember how to Wi-Fi...",
  "Detecting unauthorized vibes… ignoring them.",
  "Mapping the emotional range of ;uh...",
  "Preloading arguments from last period...",
  "Overheating the nonsense engine… cooling down...",
  "Detecting loudest possible soundboard combo...",
  "Attempting to render chaos in 144p...",
  "Disabling common sense module...",
  "Summoning ‘that one kid’ who never mutes...",
  "Connecting voice lag to your camera for extra spice...",
  "Training AI to argue with itself...",
  "Embedding chaos into the browser cache...",
  "Casting screen-sharing spells... backfired.",
  "Launching in debug mode: chaos only.",
  "Assigning vibe roles based on profile pics...",
  "Installing the ‘make everything weird’ plugin...",
  "Preparing your ears for sonic destruction...",
  "Compiling chat energy into glitch packets...",
  "Activating hallway simulator in surround sound...",
  "Slicing chaos into streamable packets...",
  "Resetting user logic... loading nonsense instead...",
  "Installing invisible lag traps...",
  "Setting max decibels to ‘someone sneezed into the mic’...",
  "Converting spilled juice on the keyboard into bugs...",
  "Unmuting everyone at once... oh no.",
  "Resurrecting old group chats for chaos nostalgia...",
  "Preparing a surprise popcat ambush...",
  "Replacing silence with awkward digital stares...",
  "Injecting extra milliseconds of voice delay...",
  "Analyzing keyboard rage patterns...",
  "Connecting chaos to the nearest available speaker...",
  "Installing meme drivers… please don’t unplug.",
  "Downloading update: adds more glitches than it fixes...",
  "Installing virtual desks... upside down.",
  "Scanning for chaos updates... found too many.",
  "Preloading accidental mic moments...",
  "Patching a bug that made everyone too normal...",
  "Disabling firewall against fun...",
  "Retuning chaos to match your mood swings...",
  "Adding 2% logic. System rejected it.",
  "Rewiring the vibe frequency...",
  "Preparing to overload your notifications...",
  "Unlocking new levels of classroom drama...",
  "Reconfiguring chaos levels to 'lunchtime mode'...",
  "Linking you to the closest chaotic neutral peer...",
  "Desyncing messages for comedic effect...",
  "Polishing randomizer with existential dread...",
  "Auto-generating homework excuses...",
  "Attempting to stabilize the meme flux capacitor...",
  "Alert: Someone just triggered ;popcat 300 times.",
  "Activating anti-focus field...",
  "Catching up to 74 missed messages from 2 minutes ago...",
  "Simulating a group project where no one contributes...",
  "Loading... but with extra reverb.",
  "Generating random usernames like 'xX_Rants420_Xx'...",
  "Applying duct tape to your digital classroom...",
  "Your Chromebook might melt. We’re not sorry.",
  "Adding 300ms lag to simulate real classroom chaos...",
  "Replacing your toolbar with chaos buttons...",
  "Tracking how fast the teacher says 'mute yourself'...",
  "Importing classroom gossip from adjacent servers...",
  "Spinning up virtual chaos hamsters...",
  "Executing random command: ;spin ;shake ;crashTab ;uh...",
  "Generating a new vibe… it’s unstable.",
  "Compiling everyone's mic static into white noise...",
  "Uploading all known cat noises to the soundboard...",
  "Turning up the gain... too late.",
  "Analyzing pixelated video feed for chaos signals...",
  "Loading an update that just adds more confusion...",
  "Channeling chaotic energy from nearby Chromebooks...",
  "Injecting just enough lag to ruin the timing...",
  "Applying glitch filter to the chat history...",
  "Slapping the server until it obeys...",
  "Encoding the entire session in 'vibe-only' mode...",
  "Encrypting your sarcasm... decrypted instantly.",
  "Bridging the gap between logic and whatever this is...",
  "Connecting your brain to the chaos cloud...",
  "Adding extra chaos to your clipboard...",
  "Compiling code made entirely of inside jokes...",
  "Trying to make sense of the soundboard... failed.",
  "Pouring energy drink into the server ports...",
  "Spawning a second version of you with a louder mic...",
  "Replaying the most cursed sound from memory...",
  "Starting cursed screen-share session...",
  "Sharing screen... and all your tabs accidentally.",
  "Projecting chaos to the entire room...",
  "Enabling 144p resolution for maximum confusion...",
  "Streaming your desktop... including your weird folder names.",
  "Starting screen-share: viewer discretion advised.",
  "Buffering cursed images… please enjoy responsibly.",
  "Sharing your screen and your secrets...",
  "Broadcasting your lag in real time...",
  "Activating screen-share... now everyone sees the chaos.",
  "Transmitting pixels cursed beyond repair...",
  "Streaming chaos in slideshow mode...",
  "Warning: your screen-share is now everyone's business.",
  "Converting your screen into a chaos beacon...",
  "Sharing your screen... accidentally showing 27 tabs.",
  "Opening screen-share… and unleashing visual noise.",
  "Sharing cursed spreadsheets and forbidden tabs...",
  "Starting screen-share: all typos now public.",
  "Screen-share initiated: hope you closed your memes folder.",
  "Launching screen-share… forgot to mute? Too late.",
  "Screen-share live! Immediately regrets everything.",
  "Transmitting forbidden vibes through your screen...",
  "Screen-sharing lag: now in HD!",
  "Showing everyone how scuffed your desktop really is...",
  "Summoning the ancient artifact known as 'My Screen'...",
  "Starting screen-share… sorry in advance.",
  "Casting cursed Chrome tabs into the void...",
  "Warning: screen-share may cause emotional damage.",
  "Streaming your screen at 1 frame per minute...",
  "Sharing screen… now everyone sees your math mistakes.",
  "Opening GVBPaint... someone's already drawing a Shrek with laser eyes.",
  "Loading cursed masterpieces from 7 different mice...",
  "Summoning shared canvas chaos...",
  "Drawing tools enabled... please use irresponsibly.",
  "GVBPaint is live — now featuring 98% chaos, 2% art.",
  "Collaborative doodling has entered the chat.",
  "Someone just filled the entire canvas with red. Again.",
  "Loading GVBPaint... eraser wars in progress.",
  "Preparing canvas for the next unholy scribble...",
  "Warning: collaborative art may cause regret.",
  "Initializing MS Paint energy with multiplayer mayhem...",
  "Synchronizing chaotic brushstrokes...",
  "Drawing live with 12 people and zero artistic restraint...",
  "GVBPaint canvas found: it's already cursed.",
  "Loading shared drawing... who drew the Among Us again?",
  "Unleashing synchronized scribbles...",
  "Fetching all known inappropriate doodles...",
  "Initializing: one canvas, infinite chaos.",
  "Someone just drew something so cursed, we’re buffering.",
  "Drawing tools syncing... get ready to overwrite each other.",
  "Turning on the lunch room conversation mode...",
  "Getting the cute cat pictures ready...",
  "Lag found. Reason: Too many people smashing the soundboard.",
  'Joining the room called "Goofy car horn sounds"...',
  "Loading 99999MB of nothing but unused code for no reason...",
  "Uploading files to server... Connection unstable.",
  "Filling the site with Jason Touch...",
  "Embedding the randomest site with the randomest rant...",
  "Oops! ChatGPT can't find the meaning of this site.",
  "Initializing the distractionator.",
  "Trying to find the start button… it ran away.",
  "Rendering chaos shaders… GPU crying softly.",
  "Downloading energy from the school vending machine…",
  "Packing your RAM full of unfiltered drama.",
  "Loading… but it's mostly just vibes and static.",
  "Reconstructing the digital cafeteria fight in 3D.",
  "Injecting caffeine into the servers… please hold.",
  "Reactivating everyone's muted mic. Accidentally.",
  "Charging the chaos batteries with hallway energy.",
  "Slipping on digital banana peels... rebooting.",
  "Initiating vibe check... system failed.",
  "Installing bug that makes everything louder.",
  "Rewriting code using pure impulse and zero logic.",
  "Trying to unmute you. Mic disagrees.",
  "Encrypting inside jokes from last semester...",
  "Trying to teach AI sarcasm. Results pending.",
  "Replaying every awkward pause at full volume.",
  "Simulating lag spikes for nostalgic effect.",
  "Turning your Chromebook into a chaos emulator.",
  "Summoning digital goblins to fix your Wi-Fi.",
  "Connecting to the nearest questionable hotspot...",
  "Routing data through a toaster... for science.",
  "Ping too high? Just call it a vibe delay.",
  "Your internet provider just rage-quit.",
  "Wi-Fi signal weaker than your math grade.",
  "Detecting 3 Chromebooks running RR+ on one desk.",
  "Sending packets of chaos to the void.",
  "Lagging on purpose for dramatic timing.",
  "Stealing Wi-Fi from the teacher’s smartboard.",
  "Server decided to go outside. We respect that.",
  "Compiling every sound you shouldn’t play in class.",
  "Mic check... it’s screaming back.",
  "Echo enabled. Now with more regret.",
  "Recording the silence between drama.",
  "Soundboard limit removed. May God help us.",
  "Reverb set to ‘haunted hallway’.",
  "Voice channel full of chaotic energy. Proceed anyway.",
  "Loading forbidden sound effects… why did we allow this?",
  "Calibrating mic to peak at all the wrong times.",
  "Auto-tuning your voice into hallway gossip.",
  "Drawing tools are live. Therapy may be required.",
  "Eraser war initiated. There will be casualties.",
  "Canvas cursed in 3... 2... now.",
  "Rendering art that would confuse your art teacher.",
  "Spray paint tool engaged. Rip your sanity.",
  "Importing doodles from the darkest timeline…",
  "Loading canvas... someone’s already written ‘Ligma’.",
  "Canvas syncing with 12 chaotic brushstrokes at once.",
  "Streaming chaos in slideshow mode...",
  "Warning: your screen-share is now everyone's business.",
  "Sharing cursed spreadsheets and forbidden tabs...",
  "Transmitting pixels cursed beyond repair...",
  "Broadcasting your lag in real time...",
];
