var e = {};
e.MAX_BIO_SIZE = 3000;
e.MIN_USERNAME_LENGTH = 3;
e.MAX_USERNAME_LENGTH = 20;
e.MIN_PASSWORD_LENGTH = 4;
e.MAX_PASSWORD_LENGTH = 20;
e.MAX_MAIL_SIZE = 1500;
e.USERNAME_CHAR_SET =
  "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890";
e.MAX_IMAGE_SIZE = 1e8;
e.MAX_PROFILE_PICTURE_SIZE = 50 * 1024; //50KB
e.MAX_DISPLAY_NAME_SIZE = 20;
e.MIN_DISPLAY_NAME_SIZE = 2;
e.ROOM_CLEANUP_TIMEOUT = 60000 * 2; // 2 minutes
module.exports = e;
