module.exports = [
  "Your tab isn't muted. Let chaos decide your fate.",
  "Today’s productivity forecast: 0% with a chance of memes.",
  "If you look busy, you *are* busy. Probably.",
  "A mysterious Chromebook update will save you from this lesson.",
  "Your teacher suspects nothing… yet.",
  "Don’t worry, the WiFi will betray you soon.",
  "Someone just Googled 'how to look productive.' It was you.",
  "That wasn’t an accident, you just discovered a new feature.",
  "This chat counts as group work if you believe hard enough.",
  "You’re one alt-tab away from a detention or a promotion.",
  "Your screen is 10% fun, 90% plausible deniability.",
  "A wild admin appears. Panic? Y/N",
  "Future you is impressed with your multitasking (and lies).",
  "Your next assignment: pretend this is for a project.",
  "Warning: You’ve reached your weekly limit of pretending to code.",
  "Your Chromebook has achieved sentience and wants snacks.",
  "You just leveled up in Avoiding Work (Level 14).",
  "Someone in this chat actually did the homework. Betrayal.",
  "Today’s secret word is 'Ctrl+Shift+W'. Use wisely.",
  "You have unlocked: Chaotic Neutral Energy™.",
  "This fortune is your hall pass now. Use it carefully.",
  "Oops. This message is being monitored by the IT Overlords.",
  "Only one of your tabs is actually related to school. Respect.",
  "Your keyboard clacking is 80% drama, 20% effort.",
  "You just convinced 3 people you’re busy. Well played.",
  "Beware of pop quizzes disguised as genuine concern.",
  "Reminder: Chrome extensions won't save you now.",
  "Your teacher thinks you’re typing notes. Sweet summer child.",
  "The firewall saw that. It’s judging you silently.",
  "A moment of silence for the assignments you never opened.",
];
